settings:
  APP_DISPLAY_NAME: Element X Nitro
  PRODUCTION_APP_NAME: Element
  APP_GROUP_IDENTIFIER: group.com.nitrovery.elementx
  BASE_BUNDLE_IDENTIFIER: com.nitrovery.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: 44QX7TX6DE
  IS_NIGHTLY_BUILD: false
  NOTIFICATION_FILTERING_ENABLED: false
